### ISSUE TITLE
Test

### ISSUE THREAD

**Issue by mjshin82** [bada-studio/labs#6]
### 1- How would you describe your DAPP?
* 'EOS Knights' is mobile RPG game that runs on the EOS platform.
* It is no different from a regular game, but it is a full-chain game that runs on an EOS smart contract.
* The players collect materials through battle in the game and craft the items to make the hero stronger.
* It is the game dApp that most users play now. (5K daily active user / 200K transaction a day)
* There is a marketplace in the game where users can trade.
![image](https://user-images.githubusercontent.com/22926212/51722825-1623ad00-209a-11e9-9133-61d53f2b6d29.png)

### 2- Where did your initial idea come from?
* A typical RPG game collects materials, craft items, and trade that.
* We thought that these things in RPGs were the suitable model to operate in the chain.
* We wanted to build a game that is a lightweight but contained the attributes of essential RPG.
![image](https://user-images.githubusercontent.com/22926212/51723822-e8d8fe00-209d-11e9-9be6-58eadee28afd.png)

### 3- Can you introduce your team and tell us what makes it special?
* 'Bada Studio' is a team with 2 members.
* Myeongjin Shin(Lead) is 10 years of experience developer, in charge of game client and smart contract development. And has worked for Naver and LINE, one of the largest IT companies in Korea.
* Seonhyang Kim(AD) is 5 years of experience conept art designer, responsible for all art in the game. And has worked for LINE.  
* And we have 4 part-timers, they build server and support UI / UX.
* I think the most important thing in the game dApp is the game itself.
* But the team need to understand the chain as well.
* The team have to think about which elements fit well in the chain.
* I think we are a team that understands them well.

![image](https://user-images.githubusercontent.com/22926212/51723688-723c0080-209d-11e9-8368-f239de999184.png)

### 4- What stage is the project at and what are your plans for scaling up?
* EOS Knights has been operating since August 2018.
* The content will continue to be added to the roadmap.
* What we focus on right now is getting a hint of Massive Adoption through this game.
* EOS is the most active platform, but the number of users is still small.
* I received a lot of feedback from users that they wanted to play our game but gave up.
* It is too difficult to create an EOS account.
* It will soon be possible to create an EOS account in the game for Facebook certified users.
* We think that game dapp is the most likely candidates for massive adoption.
* Our next games will also focus on achieving massive adoption.

### 5- Why did you decide to use blockchain technology, and specifically on EOSIO?
* In the game sector, there are many interesting things to try out in the blockchain.
* Everything is open in the blockchain.
* With these characteristics, we can design a reliable in-game economic system.
* EOSIO is the best platform for building a gaming dApp.
* Fast response speed High TPS, and strong smart contract.

### 6- How has the EOS Community responded to your project?
* Many people in the community loved our games. 
* There are  language-specific user group rooms in Telegram and WeChat.
* They provide a lot of feedback. We get a lot of ideas from user feedback for improving the game.
* Thankfully, there are also third-party sites created by users who provide stats calculators and game data statistics.
* I think it is possible because all the data is in the blockchain.
* And we will continue to try to make it be a better game as we have been doing in the meantime.

**Comment by mjshin82** [comment]
I am not used to English.
I would appreciate it if you edit the awkward sentences.

**Comment by mj-raindays** [comment]
And I will update our team picture until next Monday
